

import Layout from "./components/layout/Layout";
import "./globals.css";

 const metadata = {
  title: "Persian Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
       
      >
       <Layout> {children}</Layout>
      </body>
    </html>
  );
}
