import Layout from "./components/layout/Layout";
import "./globals.css";
import { yekan } from "@/core/utils/fonts";
const metadata = {
  title: "Persian Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <Layout> {children}</Layout>
      </body>
    </html>
  );
}
